// Copyright (c) DeltaForks Labs
// Licensed under the MIT License OR Apache 2.0.

use crate::widget::Widget;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum WidgetStructureKind {
    Column,
    Row,
    Container,
    Spacer,
    Divider,
    Text,
    Heading,
    Image,
    Button,
    ButtonContent,
    TextInput,
    PasswordInput,
    TextArea,
    SearchBar,
    Checkbox,
    Switch,
    Radio,
    Slider,
    Counter,
    Clock,
    Select,
    ProgressBar,
    Spinner,
    ScrollView,
    TableOfContents,
    TableOfContentsAccordionCollapsed,
    TableOfContentsAccordionExpanded,
    Table,
    Tooltip,
    AccordionCollapsed,
    AccordionExpanded,
    TabBar,
    ModalHidden,
    ModalVisible,
    DialogHidden,
    DialogVisible,
    Toast,
    ContextMenu,
    PopoverClosed,
    PopoverOpen,
    CarouselView,
    InteractiveCarouselView,
    VirtualList,
    VirtualListContent,
    InteractiveVirtualListContent,
    VirtualListWithSelection,
    VirtualListContentWithSelection,
    VirtualGrid,
    VirtualGridContent,
    InteractiveVirtualGridContent,
    VirtualGridWithSelection,
    VirtualGridContentWithSelection,
    DropdownMenu,
    Custom,
    PointerRegion,
}

impl WidgetStructureKind {
    pub(crate) const fn label(self) -> &'static str {
        match self {
            Self::Column => "Column",
            Self::Row => "Row",
            Self::Container => "Container",
            Self::Spacer => "Spacer",
            Self::Divider => "Divider",
            Self::Text => "Text",
            Self::Heading => "Heading",
            Self::Image => "Image",
            Self::Button => "Button",
            Self::ButtonContent => "ButtonContent",
            Self::TextInput => "TextInput",
            Self::PasswordInput => "PasswordInput",
            Self::TextArea => "TextArea",
            Self::SearchBar => "SearchBar",
            Self::Checkbox => "Checkbox",
            Self::Switch => "Switch",
            Self::Radio => "Radio",
            Self::Slider => "Slider",
            Self::Counter => "Counter",
            Self::Clock => "Clock",
            Self::Select => "Select",
            Self::ProgressBar => "ProgressBar",
            Self::Spinner => "Spinner",
            Self::ScrollView => "ScrollView",
            Self::TableOfContents => "TableOfContents",
            Self::TableOfContentsAccordionCollapsed => "TableOfContentsAccordionCollapsed",
            Self::TableOfContentsAccordionExpanded => "TableOfContentsAccordionExpanded",
            Self::Table => "Table",
            Self::Tooltip => "Tooltip",
            Self::AccordionCollapsed => "AccordionCollapsed",
            Self::AccordionExpanded => "AccordionExpanded",
            Self::TabBar => "TabBar",
            Self::ModalHidden => "ModalHidden",
            Self::ModalVisible => "ModalVisible",
            Self::DialogHidden => "DialogHidden",
            Self::DialogVisible => "DialogVisible",
            Self::Toast => "Toast",
            Self::ContextMenu => "ContextMenu",
            Self::PopoverClosed => "PopoverClosed",
            Self::PopoverOpen => "PopoverOpen",
            Self::CarouselView => "CarouselView",
            Self::InteractiveCarouselView => "InteractiveCarouselView",
            Self::VirtualList => "VirtualList",
            Self::VirtualListContent => "VirtualListContent",
            Self::InteractiveVirtualListContent => "InteractiveVirtualListContent",
            Self::VirtualListWithSelection => "VirtualListWithSelection",
            Self::VirtualListContentWithSelection => "VirtualListContentWithSelection",
            Self::VirtualGrid => "VirtualGrid",
            Self::VirtualGridContent => "VirtualGridContent",
            Self::InteractiveVirtualGridContent => "InteractiveVirtualGridContent",
            Self::VirtualGridWithSelection => "VirtualGridWithSelection",
            Self::VirtualGridContentWithSelection => "VirtualGridContentWithSelection",
            Self::DropdownMenu => "DropdownMenu",
            Self::Custom => "Custom",
            Self::PointerRegion => "PointerRegion",
        }
    }
}

pub(crate) fn widget_structure_kind<Msg>(widget: &Widget<'_, Msg>) -> WidgetStructureKind {
    use WidgetStructureKind as Kind;
    match widget {
        Widget::Column { .. } => Kind::Column,
        Widget::Row { .. } => Kind::Row,
        Widget::Container { .. } => Kind::Container,
        Widget::Spacer { .. } => Kind::Spacer,
        Widget::Divider { .. } => Kind::Divider,
        Widget::Text { .. } | Widget::RichText { .. } => Kind::Text,
        Widget::Heading { .. } => Kind::Heading,
        Widget::Image { .. } => Kind::Image,
        Widget::Button { .. } => Kind::Button,
        Widget::ButtonContent { .. } => Kind::ButtonContent,
        Widget::TextInput {
            is_password: true, ..
        } => Kind::PasswordInput,
        Widget::TextInput { .. } => Kind::TextInput,
        Widget::TextArea { .. } => Kind::TextArea,
        Widget::SearchBar { .. } => Kind::SearchBar,
        Widget::Checkbox { .. } => Kind::Checkbox,
        Widget::Switch { .. } => Kind::Switch,
        Widget::Radio { .. } => Kind::Radio,
        Widget::Slider { .. } => Kind::Slider,
        Widget::Counter { .. } => Kind::Counter,
        Widget::Clock { .. } => Kind::Clock,
        Widget::Select { .. } => Kind::Select,
        Widget::ProgressBar { .. } => Kind::ProgressBar,
        Widget::Spinner { .. } => Kind::Spinner,
        Widget::ScrollView { .. } => Kind::ScrollView,
        Widget::TableOfContents { .. } if widget.table_of_contents_accordion().is_some() => {
            if widget.table_of_contents_entries_visible() {
                Kind::TableOfContentsAccordionExpanded
            } else {
                Kind::TableOfContentsAccordionCollapsed
            }
        }
        Widget::TableOfContents { .. } => Kind::TableOfContents,
        Widget::Table { .. } => Kind::Table,
        Widget::Tooltip { .. } => Kind::Tooltip,
        Widget::Accordion { expanded: true, .. } => Kind::AccordionExpanded,
        Widget::Accordion { .. } => Kind::AccordionCollapsed,
        Widget::TabBar { .. } => Kind::TabBar,
        Widget::Modal { visible: true, .. } => Kind::ModalVisible,
        Widget::Modal { .. } => Kind::ModalHidden,
        Widget::Dialog { visible: true, .. } => Kind::DialogVisible,
        Widget::Dialog { .. } => Kind::DialogHidden,
        Widget::Toast { .. } => Kind::Toast,
        Widget::ContextMenu { .. } => Kind::ContextMenu,
        Widget::DropdownMenu { .. } => Kind::DropdownMenu,
        Widget::Custom { .. } => Kind::Custom,
        Widget::PointerRegion { .. } => Kind::PointerRegion,
        Widget::Popover { open: true, .. } => Kind::PopoverOpen,
        Widget::Popover { .. } => Kind::PopoverClosed,
        Widget::CarouselView { .. } => Kind::CarouselView,
        Widget::InteractiveCarouselView { .. } => Kind::InteractiveCarouselView,
        Widget::VirtualList { .. } => Kind::VirtualList,
        Widget::VirtualListContent { .. } => Kind::VirtualListContent,
        Widget::InteractiveVirtualListContent { .. } => Kind::InteractiveVirtualListContent,
        Widget::VirtualListWithSelection { .. } => Kind::VirtualListWithSelection,
        Widget::VirtualListContentWithSelection { .. } => Kind::VirtualListContentWithSelection,
        Widget::VirtualGrid { .. } => Kind::VirtualGrid,
        Widget::VirtualGridContent { .. } => Kind::VirtualGridContent,
        Widget::InteractiveVirtualGridContent { .. } => Kind::InteractiveVirtualGridContent,
        Widget::VirtualGridWithSelection { .. } => Kind::VirtualGridWithSelection,
        Widget::VirtualGridContentWithSelection { .. } => Kind::VirtualGridContentWithSelection,
    }
}
