// Copyright (c) DeltaForks Labs
// Licensed under the MIT License OR Apache 2.0.

use winit::keyboard::{Key, ModifiersState, NamedKey};

/// A logical key that can participate in a surface-local application shortcut.
///
/// Character values preserve the logical text produced by the active keyboard
/// layout; they are not physical scan codes.
///
/// ```rust
/// use rutter::{ShortcutKey, ShortcutNamedKey};
///
/// assert_eq!(ShortcutKey::Character("p".into()), ShortcutKey::Character("p".into()));
/// assert_eq!(ShortcutKey::Named(ShortcutNamedKey::Escape), ShortcutKey::Named(ShortcutNamedKey::Escape));
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum ShortcutKey {
    /// A layout-aware character sequence produced by the logical key.
    Character(String),
    /// A portable non-text key.
    Named(ShortcutNamedKey),
    /// A dead key that may participate in a later text composition.
    Dead(Option<char>),
    /// A key without a portable logical representation.
    Unidentified,
}

/// Portable named keys normalized for application shortcuts.
///
/// ```rust
/// use rutter::{ShortcutKey, ShortcutNamedKey};
///
/// let escape = ShortcutKey::Named(ShortcutNamedKey::Escape);
/// assert!(matches!(escape, ShortcutKey::Named(ShortcutNamedKey::Escape)));
/// ```
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShortcutNamedKey {
    /// Backspace deletes the preceding character in text controls.
    Backspace,
    /// Tab usually moves focus between controls.
    Tab,
    /// Enter activates or submits a focused control.
    Enter,
    /// Escape dismisses a surface-local view or overlay.
    Escape,
    /// The space bar.
    Space,
    /// The upward arrow key.
    ArrowUp,
    /// The downward arrow key.
    ArrowDown,
    /// The leftward arrow key.
    ArrowLeft,
    /// The rightward arrow key.
    ArrowRight,
    /// The Home key.
    Home,
    /// The End key.
    End,
    /// The Page Up key.
    PageUp,
    /// The Page Down key.
    PageDown,
    /// The Insert key.
    Insert,
    /// The Delete key.
    Delete,
    /// One of the portable F1 through F12 function keys.
    Function(u8),
    /// A named key without a stable Rutter representation.
    Other,
}

/// A normalized pressed-key event delivered to an application shortcut hook.
///
/// It is limited to the focused Rutter surface and does not register a
/// desktop-wide hotkey with the compositor or operating system.
///
/// ```rust
/// use rutter::{ShortcutEvent, ShortcutKey, ShortcutNamedKey};
///
/// let event = ShortcutEvent {
///     key: ShortcutKey::Named(ShortcutNamedKey::Escape),
///     control: false,
///     alt: false,
///     shift: false,
///     super_key: false,
///     repeat: false,
/// };
/// assert!(!event.repeat);
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ShortcutEvent {
    /// The normalized logical key.
    pub key: ShortcutKey,
    /// Whether the Control modifier was held.
    pub control: bool,
    /// Whether the Alt modifier was held.
    pub alt: bool,
    /// Whether the Shift modifier was held.
    pub shift: bool,
    /// Whether the platform Super, Meta, or Command modifier was held.
    pub super_key: bool,
    /// Whether this press was generated by key auto-repeat.
    pub repeat: bool,
}

/// The result of matching a surface-local application shortcut.
///
/// ```rust
/// use rutter::ShortcutOutcome;
///
/// let outcome: ShortcutOutcome<()> = ShortcutOutcome::Consumed;
/// assert!(matches!(outcome, ShortcutOutcome::Consumed));
/// ```
#[derive(Clone, Debug, PartialEq, Eq)]
#[must_use = "shortcut outcomes must be returned to the Rutter runtime"]
pub enum ShortcutOutcome<Message> {
    /// Leave the event to text input, focus traversal, and built-in widgets.
    Ignored,
    /// Dispatch this application message through the normal update path and consume the event.
    Message(Message),
    /// Consume the event without dispatching a message, such as to suppress a repeat.
    Consumed,
}

pub(crate) fn shortcut_event_from_winit(
    logical_key: &Key,
    modifiers: ModifiersState,
    repeat: bool,
) -> ShortcutEvent {
    ShortcutEvent {
        key: shortcut_key_from_winit(logical_key),
        control: modifiers.control_key(),
        alt: modifiers.alt_key(),
        shift: modifiers.shift_key(),
        super_key: modifiers.super_key(),
        repeat,
    }
}

fn shortcut_key_from_winit(logical_key: &Key) -> ShortcutKey {
    match logical_key {
        Key::Character(character) => ShortcutKey::Character(character.to_string()),
        Key::Named(named_key) => ShortcutKey::Named(shortcut_named_key_from_winit(*named_key)),
        Key::Dead(character) => ShortcutKey::Dead(*character),
        Key::Unidentified(_) => ShortcutKey::Unidentified,
    }
}

const PORTABLE_NAMED_KEYS: [(NamedKey, ShortcutNamedKey); 15] = [
    (NamedKey::Backspace, ShortcutNamedKey::Backspace),
    (NamedKey::Tab, ShortcutNamedKey::Tab),
    (NamedKey::Enter, ShortcutNamedKey::Enter),
    (NamedKey::Escape, ShortcutNamedKey::Escape),
    (NamedKey::Space, ShortcutNamedKey::Space),
    (NamedKey::ArrowUp, ShortcutNamedKey::ArrowUp),
    (NamedKey::ArrowDown, ShortcutNamedKey::ArrowDown),
    (NamedKey::ArrowLeft, ShortcutNamedKey::ArrowLeft),
    (NamedKey::ArrowRight, ShortcutNamedKey::ArrowRight),
    (NamedKey::Home, ShortcutNamedKey::Home),
    (NamedKey::End, ShortcutNamedKey::End),
    (NamedKey::PageUp, ShortcutNamedKey::PageUp),
    (NamedKey::PageDown, ShortcutNamedKey::PageDown),
    (NamedKey::Insert, ShortcutNamedKey::Insert),
    (NamedKey::Delete, ShortcutNamedKey::Delete),
];

const FUNCTION_KEYS: [NamedKey; 12] = [
    NamedKey::F1,
    NamedKey::F2,
    NamedKey::F3,
    NamedKey::F4,
    NamedKey::F5,
    NamedKey::F6,
    NamedKey::F7,
    NamedKey::F8,
    NamedKey::F9,
    NamedKey::F10,
    NamedKey::F11,
    NamedKey::F12,
];

fn shortcut_named_key_from_winit(named_key: NamedKey) -> ShortcutNamedKey {
    find_portable_named_key(named_key)
        .or_else(|| shortcut_function_number(named_key).map(ShortcutNamedKey::Function))
        .unwrap_or(ShortcutNamedKey::Other)
}

fn find_portable_named_key(named_key: NamedKey) -> Option<ShortcutNamedKey> {
    PORTABLE_NAMED_KEYS
        .iter()
        .find_map(|(source, normalized)| (*source == named_key).then_some(*normalized))
}

fn shortcut_function_number(named_key: NamedKey) -> Option<u8> {
    FUNCTION_KEYS
        .iter()
        .position(|source| *source == named_key)
        .map(|index| index as u8 + 1)
}

#[cfg(test)]
mod tests {
    use winit::keyboard::{Key, ModifiersState, NamedKey};

    use super::{ShortcutKey, ShortcutNamedKey, shortcut_event_from_winit};

    #[test]
    fn normalizes_layout_aware_characters_and_modifier_state() {
        let modifiers = ModifiersState::CONTROL | ModifiersState::SHIFT;
        let event = shortcut_event_from_winit(&Key::Character("ç".into()), modifiers, true);

        assert_eq!(event.key, ShortcutKey::Character("ç".into()));
        assert!(event.control);
        assert!(!event.alt);
        assert!(event.shift);
        assert!(!event.super_key);
        assert!(event.repeat);
    }

    #[test]
    fn normalizes_portable_named_keys_without_character_fallback() {
        let event =
            shortcut_event_from_winit(&Key::Named(NamedKey::Escape), ModifiersState::SUPER, false);

        assert_eq!(event.key, ShortcutKey::Named(ShortcutNamedKey::Escape));
        assert!(event.super_key);
    }

    #[test]
    fn groups_function_keys_under_their_portable_number() {
        let event =
            shortcut_event_from_winit(&Key::Named(NamedKey::F5), ModifiersState::empty(), false);

        assert_eq!(event.key, ShortcutKey::Named(ShortcutNamedKey::Function(5)));
    }
}
