// Copyright (c) DeltaForks Labs
// Licensed under the MIT License OR Apache 2.0.

use crate::widget::Widget;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum WidgetStructureKind {
    Column,
    Row,
    Container,
    Spacer,
    Divider,
    Text,
    Image,
    Button,
    ButtonContent,
    TextInput,
    PasswordInput,
    TextArea,
    SearchBar,
    Checkbox,
    Switch,
    Radio,
    Slider,
    Select,
    ProgressBar,
    Spinner,
    ScrollView,
    Tooltip,
    AccordionCollapsed,
    AccordionExpanded,
    TabBar,
    ModalHidden,
    ModalVisible,
    DialogHidden,
    DialogVisible,
    Toast,
    ContextMenu,
    PopoverClosed,
    PopoverOpen,
    VirtualList,
    VirtualListContent,
    VirtualGrid,
    VirtualGridContent,
}

impl WidgetStructureKind {
    pub(crate) const fn label(self) -> &'static str {
        match self {
            Self::Column => "Column",
            Self::Row => "Row",
            Self::Container => "Container",
            Self::Spacer => "Spacer",
            Self::Divider => "Divider",
            Self::Text => "Text",
            Self::Image => "Image",
            Self::Button => "Button",
            Self::ButtonContent => "ButtonContent",
            Self::TextInput => "TextInput",
            Self::PasswordInput => "PasswordInput",
            Self::TextArea => "TextArea",
            Self::SearchBar => "SearchBar",
            Self::Checkbox => "Checkbox",
            Self::Switch => "Switch",
            Self::Radio => "Radio",
            Self::Slider => "Slider",
            Self::Select => "Select",
            Self::ProgressBar => "ProgressBar",
            Self::Spinner => "Spinner",
            Self::ScrollView => "ScrollView",
            Self::Tooltip => "Tooltip",
            Self::AccordionCollapsed => "AccordionCollapsed",
            Self::AccordionExpanded => "AccordionExpanded",
            Self::TabBar => "TabBar",
            Self::ModalHidden => "ModalHidden",
            Self::ModalVisible => "ModalVisible",
            Self::DialogHidden => "DialogHidden",
            Self::DialogVisible => "DialogVisible",
            Self::Toast => "Toast",
            Self::ContextMenu => "ContextMenu",
            Self::PopoverClosed => "PopoverClosed",
            Self::PopoverOpen => "PopoverOpen",
            Self::VirtualList => "VirtualList",
            Self::VirtualListContent => "VirtualListContent",
            Self::VirtualGrid => "VirtualGrid",
            Self::VirtualGridContent => "VirtualGridContent",
        }
    }
}

pub(crate) fn widget_structure_kind<Msg>(widget: &Widget<'_, Msg>) -> WidgetStructureKind {
    use WidgetStructureKind as Kind;
    match widget {
        Widget::Column { .. } => Kind::Column,
        Widget::Row { .. } => Kind::Row,
        Widget::Container { .. } => Kind::Container,
        Widget::Spacer { .. } => Kind::Spacer,
        Widget::Divider { .. } => Kind::Divider,
        Widget::Text { .. } | Widget::StrongText { .. } => Kind::Text,
        Widget::Image { .. } => Kind::Image,
        Widget::Button { .. } => Kind::Button,
        Widget::ButtonContent { .. } => Kind::ButtonContent,
        Widget::TextInput {
            is_password: true, ..
        } => Kind::PasswordInput,
        Widget::TextInput { .. } => Kind::TextInput,
        Widget::TextArea { .. } => Kind::TextArea,
        Widget::SearchBar { .. } => Kind::SearchBar,
        Widget::Checkbox { .. } => Kind::Checkbox,
        Widget::Switch { .. } => Kind::Switch,
        Widget::Radio { .. } => Kind::Radio,
        Widget::Slider { .. } => Kind::Slider,
        Widget::Select { .. } => Kind::Select,
        Widget::ProgressBar { .. } => Kind::ProgressBar,
        Widget::Spinner { .. } => Kind::Spinner,
        Widget::ScrollView { .. } => Kind::ScrollView,
        Widget::Tooltip { .. } => Kind::Tooltip,
        Widget::Accordion { expanded: true, .. } => Kind::AccordionExpanded,
        Widget::Accordion { .. } => Kind::AccordionCollapsed,
        Widget::TabBar { .. } => Kind::TabBar,
        Widget::Modal { visible: true, .. } => Kind::ModalVisible,
        Widget::Modal { .. } => Kind::ModalHidden,
        Widget::Dialog { visible: true, .. } => Kind::DialogVisible,
        Widget::Dialog { .. } => Kind::DialogHidden,
        Widget::Toast { .. } => Kind::Toast,
        Widget::ContextMenu { .. } => Kind::ContextMenu,
        Widget::Popover { open: true, .. } => Kind::PopoverOpen,
        Widget::Popover { .. } => Kind::PopoverClosed,
        Widget::VirtualList { .. } => Kind::VirtualList,
        Widget::VirtualListContent { .. } => Kind::VirtualListContent,
        Widget::VirtualGrid { .. } => Kind::VirtualGrid,
        Widget::VirtualGridContent { .. } => Kind::VirtualGridContent,
    }
}
